### PR TITLE
Update .gitignore with more files

### PR DESCRIPTION
**Pull request by kenzierocks**
Currently, when testing WorldEdit I get upwards of 1000 files that I need to make sure I don't commit. This gitignore patch will ignore those files.

### CODE REVIEW

**Comment by wizjany** [comment]
._. how exactly do you test worldedit?

**Comment by kenzierocks** [comment]
1) With the Run button in Eclipse, it's easiest and I know of no other way.
2) Really? I'll update that exclude then.

**Comment by kenzierocks** [comment]
Okay, should be good now.

**Comment by wizjany** [comment]
Hm, I can't remember eclipse making random stuff like that. Do you have your run configuration set to startup a server or something? Maybe you need to change the working directory?

**Comment by kenzierocks** [comment]
It runs a full Forge client. I could change the directory, but that breaks things if I remember.

**Comment by wizjany** [comment]
I feel like these are some rather generic folders that would be better suited for your personal excludes file.

**Comment by kenzierocks** [comment]
You can do nested personal excludes?

**Comment by kenzierocks** [comment]
Well, that closed that. I'll do it locally.

**Pull request closed without merging**
