### PR TITLE
Forge 1.9 branch updated to 12.16.0.1816 version

### PR DESCRIPTION
**Pull request by FRedEnergy**
Since 12.16.0.1770 Forge guys made couple of fields private and added getters for them. That made first builds of 1.9 incompatible with the subsequent. I decided to update to the latest Forge. Hope it will help.

### CODE REVIEW

**Comment by wizjany** [comment]
https://github.com/sk89q/WorldEdit/tree/feature/forge-1.9 ?

**Comment by wizjany** [comment]
can you squash your second commit

**Comment by FRedEnergy** [comment]
Done

**Comment by kenzierocks** [comment]
Thanks!

**Pull request merged**
