### PR TITLE
Update Forge to 1.10.2

### PR DESCRIPTION
**Pull request by kenzierocks**
Mostly works, I think brushes might be broken again. Testing by people more experienced with the brushes is probably needed.

### CODE REVIEW

**Comment by falukerites** [comment]
**No need for this, 1.10 works with the 1.9.4 version**

**Comment by kenzierocks** [comment]
That's incorrect, TileEntity.create's signature changed. I'm 99% sure that copying chests + signs + other TEs would be broken.

**Comment by wizjany** [comment]
despite what forge might have you believe, a lot of signatures and so on have changed between 1.9, 1.9.4, and 1.10, which they for some reason wrap up into one version.

**Comment by wizjany** [comment]
Going to merge and release tomorrow (today) unless there's any objections.

**Comment by kenzierocks** [comment]
@wizjany Want to merge it?

**Comment by wizjany** [comment]
Oh yea legion came out and I forgot about everything else.

**Pull request merged**
