### PR TITLE
[Request] Please just give me the issue tracker link...

### PR DESCRIPTION
**Pull request by PrismaticYT**
You expect me to know where it is?

### CODE REVIEW

**Comment by kashike** [comment]
-.-

**Comment by PrismaticYT** [comment]
Also, I don't want to make an account on some obscure site.

**Comment by me4502** [comment]
It's linked in the readme on github.

**Comment by PrismaticYT** [comment]
I still don't want to make an account on some obscure site..

**Comment by zml2008** [comment]
sounds like a you problem

**Pull request closed without merging**
