### PR TITLE
Add spigot_v1_8_R3 adapter.

### PR DESCRIPTION
**Pull request by twizmwazin**
This pull request adds a spigot_v1_8_R3 adapter.

### CODE REVIEW

**Comment by sk89q** [comment]
@ other WE devs: we should compile this ourselves for security reasons

**Comment by luacs1998** [comment]
Though, why would someone PR a class file into the upstream project, as opposed to just providing unofficial builds?

**Comment by DarkArc** [comment]
@luacs1998 You mean maliciously? It's a matter of distribution, if you can "infect" the official build, then there's a potential for the vast majority of users to become victims -- not just those whom were too impatient to wait for an official release.

**Comment by PikachuEXE** [comment]
I wonder if there is a proper process for this kind of PR (which involves class file not source code)

**Comment by sk89q** [comment]
Well, someone submitting a PR to the adapters repo probably means that we should compile it and put it in WE.

**Comment by TheMolkaPL** [comment]
@wizjany pushed it in a3a40396469a143fa56bf121a05f1498cd927ccf.

Can be closed. :apple:

**Pull request closed without merging**
