### PR TITLE
GPLv3 Markdown

### PR DESCRIPTION
**Pull request by DMP9-MC**
This PR rewrites the LICENCE file in markdown format.

### CODE REVIEW

**Comment by wizjany** [comment]
you just copy-pasted the whole thing and didn't even bother to re-instate the other licenses...

**Comment by DMP9-MC** [comment]
It would be nice if you linked me to said licences and/or give me the names
of them

**Comment by kashike** [comment]
Use your eyes.
https://github.com/sk89q/WorldEdit/blob/master/LICENSE.txt#L2
https://github.com/sk89q/WorldEdit/blob/master/LICENSE.txt#L175
https://github.com/sk89q/WorldEdit/blob/master/LICENSE.txt#L802
https://github.com/sk89q/WorldEdit/blob/master/LICENSE.txt#L836

**Comment by DMP9-MC** [comment]
Updated the PR accordingly -- I thought the whole document was just GPL, sorry.

**Comment by sk89q** [comment]
You even got the wrong license. 

I'm for rejecting this PR because changes to documents like this need to be done by a dev member from scratch and never via PR.

**Comment by DMP9-MC** [comment]
> It's not GPL

Then why is the WorldEdit licence [line 175](https://github.com/sk89q/WorldEdit/blob/master/LICENSE.txt#L175) a copy of GPL?

**Comment by kenzierocks** [comment]
@DMP9-MC You wrote the top-level license as GPL, when [it's LGPL](https://github.com/sk89q/WorldEdit/blob/master/LICENSE.txt#L7). Most of the code has an LGPL header as well.

**Comment by DMP9-MC** [comment]
@kenzierocks I misinterpreted the

    
                    GNU GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007

**Pull request closed without merging**
