### PR TITLE
Add world flag

### PR DESCRIPTION
**Pull request by kenzierocks**
As per PseudoKnight's suggestion on [WORLDEDIT-3241](http://youtrack.sk89q.com/issue/WORLDEDIT-3241), this adds a flag for globally butchering, which is normally done by changing the default to -1 in the config.

### CODE REVIEW

**Comment by TheMolkaPL** [comment]
:+1:

**Comment by wizjany** [comment]
I feel as if this is a bit redundant. We're not really even saving typing time vs. doing -1. The suggestion on the linked issue was simply because someone used //butcher 5000, where //butcher -1 would have worked fine (I believe PseudoKnight just overlooked the presence of -1).

**Comment by kenzierocks** [comment]
You actually can't use -1, that chooses the max radius.

**Comment by wizjany** [comment]
Which defaults to the whole (loaded) world. If someone changes the max in their config, the -w flag would bypass that. This is more about loading chunks.

**Comment by kenzierocks** [comment]
I see. Permissions maybe?

**Comment by kenzierocks** [comment]
Should I close this or redo the commits?

**Comment by kenzierocks** [comment]
Closing this, merge is a mess.

**Comment by wizjany** [comment]
As I said before, I don't see any need for the feature.

**Pull request closed without merging**
