### PR TITLE
Update Sponge WorldEdit to 1.10 and 1.11

### PR DESCRIPTION
**Pull request by me4502**
This also adds an adapter system, akin to the Spigot version, that allows it to function across multiple versions.

### CODE REVIEW

**Comment by me4502** [comment]
I just realized, this shouldn't work should it? It's a MCP named class file being loaded in SF & SV.. Yet it does? Anyone know why this could be?

**Comment by me4502** [comment]
In my opinion it's a lot better than the alternative.

**Comment by DarkArc** [comment]
Well, unlike bukkit, a Sponge update normally requires both API changes, and NMS changes. The adapter only helps with NMS, I feel like it's a false sense of cross version stability.

**Comment by wizjany** [comment]
@DarkArc @me4502 status on this? as noted, WE 6 API still uses int IDs, so the adapter system is probably as good as it gets. are there any other concerns before pulling this?

**Comment by me4502** [comment]
This doesn't currently work - so I wouldn't pull it just yet. I've been super busy, but basically the issue is that because 1.10 and 1.11 are similar, it's loading the 1.11 one on 1.10. It needs a way to determine which is the correct one to load, other than it erroring on class load.

**Comment by me4502** [comment]
Moved to the sponge-adapter branch.

**Pull request closed without merging**
