### PR TITLE
//schematic list with pages

### PR DESCRIPTION
**Pull request by BangL**
New command argument: "page"
new syntax:
	//schematic list [page] [flags]

"schematic list" shows always page 1 now.

### CODE REVIEW

**Comment by kenzierocks** [comment]
If wanted I could work this in.

**Comment by TomyLobo** [comment]
since @BangL seems to have abandoned it, I'd say it's up for grabs, @kenzierocks (and others)

**Comment by kenzierocks** [comment]
I will update + integrate it.

**Comment by TomyLobo** [comment]
cool

**Comment by kenzierocks** [comment]
Continue discussion in #338.

**Pull request closed without merging**
