### PR TITLE
[Request] 1.8.9 Block ID patch

### PR DESCRIPTION
**Pull request by PrismaticYT**
Can someone change the block ID limit in the Forge 1.8.9 version's Block.java to 32767 and provide me with a USABLE mod that I can put in /home/CENSOREDSODONTEVENTHINKABOUTIT!!!/.minecraft/mods?

### CODE REVIEW

**Comment by PrismaticYT** [comment]
Also, this is basically an issue. for SOME WEIRD REASON there's no issues folder???

**Comment by kenzierocks** [comment]
No, that's a Minecraft limit.

**Comment by PrismaticYT** [comment]
No it's not. MInecraft can support block IDs above 4095.

**Comment by zml2008** [comment]
then either create an issue on WE's actual issue tracker (hint: it's not on GH), or create and test a patch that will add support to WE and submit it as an actual PR.

**Comment by PrismaticYT** [comment]
I'd do it myself but I don't know how to decompile the forge jar file, edit Block.java, then recompile it.

**Comment by PrismaticYT** [comment]
Also, why isn't the issue tracker on github? (What's GH?) Can you link me the issue tracker?

**Comment by zml2008** [comment]
ok so if you're trying to edit forge classes then that's way out of scope of WE. If this an actual WE issue, I believe in your ability to find a link to the issue tracker and post the issue correctly.

**Pull request closed without merging**
